ALTER TYPE "ServerMemberRole" ADD VALUE IF NOT EXISTS 'MODERATOR' AFTER 'OWNER';
ALTER TYPE "ServerMemberRole" ADD VALUE IF NOT EXISTS 'ADMIN' AFTER 'OWNER';
ALTER TYPE "ServerMemberRole" ADD VALUE IF NOT EXISTS 'READ_ONLY' AFTER 'MEMBER';
ALTER TYPE "MessageKind" ADD VALUE IF NOT EXISTS 'GROUP';
